version: '3'
services:
  confortui:
    image: confortui:1.0
    build:
      context: ./UI
      dockerfile: Dockerfile
    container_name: confortui
  token_server:
    image: tokenserver:1.0
    build:
      context: ./TokenServer
      dockerfile: Dockerfile
    container_name: token_server
    env_file:
      - CREDS.env
  nginx:
    image: nginx:stable-alpine-slim
    container_name: nginxv2
    ports:
      - "5000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
